<template>
  <div class="w-[80%] mx-auto">
    <h1 class="font-bold text-xl">Privacy Policy</h1>
    <p class="my-5">Last updated: Oct 5, 2024</p>
    <p>
      This Privacy Policy describes Our policies and procedures on the
      collection, use and disclosure of Your information when You use the
      Service and tells You about Your privacy rights and how the law protects
      You.
    </p>
    <p class="my-3">
      We use Your Personal data to provide and improve the Service. By using the
      Service, You agree to the collection and use of information in accordance
      with this Privacy Policy. This Privacy Policy has been created with the
      help of the
      <a
        href="https://www.termsfeed.com/privacy-policy-generator/"
        target="_blank"
        >Privacy Policy Generator</a
      >.
    </p>
    <h2>Interpretation and Definitions</h2>
    <h3>Interpretation</h3>
    <p>
      The words of which the initial letter is capitalized have meanings defined
      under the following conditions. The following definitions shall have the
      same meaning regardless of whether they appear in singular or in plural.
    </p>
    <h3 class="text-lg font-bold mt-5">Definitions</h3>
    <p>For the purposes of this Privacy Policy:</p>
    <ul class="list-disc ml-5">
      <li>
        <p>
          <strong>Company</strong> (referred to as either &quot;the
          Company&quot;, &quot;We&quot;, &quot;Us&quot; or &quot;Our&quot; in
          this Agreement) refers to DZ Grainalyzer.
        </p>
      </li>
      <li>
        <p>
          <strong>Cookies</strong> are small files that are placed on Your
          computer, mobile device or any other device by a website, containing
          the details of Your browsing history on that website among its many
          uses.
        </p>
      </li>
      <li>
        <p><strong>Country</strong> refers to: British Columbia, Canada</p>
      </li>
      <li>
        <p>
          <strong>Device</strong> means any device that can access the Service
          such as a computer, a cellphone or a digital tablet.
        </p>
      </li>
      <li>
        <p>
          <strong>Personal Data</strong> is any information that relates to an
          identified or identifiable individual.
        </p>
      </li>
      <li>
        <p><strong>Service</strong> refers to the Website.</p>
      </li>
      <li>
        <p>
          <strong>Service Provider</strong> means any natural or legal person
          who processes the data on behalf of the Company. It refers to
          third-party companies or individuals employed by the Company to
          facilitate the Service, to provide the Service on behalf of the
          Company, to perform services related to the Service or to assist the
          Company in analyzing how the Service is used.
        </p>
      </li>
      <li>
        <p>
          <strong>Usage Data</strong> refers to data collected automatically,
          either generated by the use of the Service or from the Service
          infrastructure itself (for example, the duration of a page visit). It
          also refers to the file uploaded in order to use the service.
        </p>
      </li>
      <li>
        <p>
          <strong>Email</strong> refers to the email we optionally collect to
          contact you after the report is ready. It will be stored on the server
          temporarily for 7 days from when you request the report.
        </p>
      </li>
      <li>
        <p>
          <strong>Website</strong> refers to DZ Grainalyzer, accessible from
          <a
            href="https://dzgrainalyzer.eoas.ubc.ca"
            rel="external nofollow noopener"
            target="_blank"
            >https://dzgrainalyzer.eoas.ubc.ca</a
          >
        </p>
      </li>
      <li>
        <p>
          <strong>You</strong> means the individual accessing or using the
          Service, or the company, or other legal entity on behalf of which such
          individual is accessing or using the Service, as applicable.
        </p>
      </li>
    </ul>
    <h2 class="font-bold text-lg mt-5">
      Collecting and Using Your Personal Data
    </h2>
    <h3 class="text-md font-bold">Types of Data Collected</h3>
    <h4>Personal Data</h4>
    <p>
      While using Our Service, We may ask You to provide Us with certain
      personally identifiable information that can be used to contact or
      identify You. Personally identifiable information may include, but is not
      limited to:
    </p>
    <div class="ml-5">
      <h4 class="font-bold">Usage Data</h4>
      <p>Usage Data is collected automatically when using the Service.</p>
      <p>Includes the excel file uploaded to use the service.</p>
      <p>
        Usage Data may include information such as Your Device's Internet
        Protocol address (e.g. IP address), browser type, browser version, the
        pages of our Service that You visit, the time and date of Your visit,
        the time spent on those pages, unique device identifiers and other
        diagnostic data.
      </p>
      <p>
        When You access the Service by or through a mobile device, We may
        collect certain information automatically, including, but not limited
        to, the type of mobile device You use, Your mobile device unique ID, the
        IP address of Your mobile device, Your mobile operating system, the type
        of mobile Internet browser You use, unique device identifiers and other
        diagnostic data.
      </p>
      <p>
        We may also collect information that Your browser sends whenever You
        visit our Service or when You access the Service by or through a mobile
        device.
      </p>
    </div>
    <div class="ml-5">
      <h4 class="font-bold">Email</h4>
      <p>
        We collect emails to notify the user when the report is ready. This
        information is optional and is only used to notify the user when the
        report is ready. It will be stored on the server temporarily for 7 days
        from creation of report.
      </p>
    </div>
    <h4 class="font-bold">Tracking Technologies and Cookies</h4>
    <p>
      We do not use Cookies and similar tracking technologies to track the
      activity on Our Service and store certain information. We only track
      anonymous usage data.
    </p>
    <br />
    <h3 class="font-bold">Use of Your Personal Data</h3>
    <p>The Company may use Personal Data for the following purposes:</p>
    <ul class="ml-5">
      <li>
        <p>
          <strong>To provide and maintain our Service</strong>, including to
          monitor the usage of our Service.
        </p>
      </li>
    </ul>
    <br />
    <h3 class="font-bold">Retention of Your Personal Data</h3>
    <p>
      The Company will retain Your Personal Data only for as long as is
      necessary for the purposes set out in this Privacy Policy. We will retain
      and use Your uploaded files on server for 7 days or less. Anonymous
      analaytics might be stored for longer.
    </p>
    <br />
    <h3 class="font-bold">Transfer of Your Personal Data</h3>
    <p>
      Your information, including Personal Data, is processed at the Company's
      operating offices and in any other places where the parties involved in
      the processing are located. It means that this information may be
      transferred to — and maintained on — computers located outside of Your
      state, province, country or other governmental jurisdiction where the data
      protection laws may differ than those from Your jurisdiction.
    </p>
    <p>
      Your consent to this Privacy Policy followed by Your submission of such
      information represents Your agreement to that transfer.
    </p>
    <p>
      The Company will take all steps reasonably necessary to ensure that Your
      data is treated securely and in accordance with this Privacy Policy and no
      transfer of Your Personal Data will take place to an organization or a
      country unless there are adequate controls in place including the security
      of Your data and other personal information.
    </p>
    <br />
    <h3 class="font-bold">Delete Your Personal Data</h3>
    <p>
      We do not persist any identifiable data, so there is no need to request a
      deletion. The uploaded files and provided email are deleted after 7 days
      or less.
    </p>
    <br />

    <h4 class="font-bold">Other legal requirements</h4>
    <p>
      The Company may disclose Your Personal Data in the good faith belief that
      such action is necessary to:
    </p>
    <ul>
      <li>Comply with a legal obligation</li>
      <li>Protect and defend the rights or property of the Company</li>
      <li>
        Prevent or investigate possible wrongdoing in connection with the
        Service
      </li>
      <li>Protect the personal safety of Users of the Service or the public</li>
      <li>Protect against legal liability</li>
    </ul>
    <br />
    <h3 class="font-bold">Security of Your Personal Data</h3>
    <p>
      The security of Your Personal Data is important to Us, but remember that
      no method of transmission over the Internet, or method of electronic
      storage is 100% secure. While We strive to use commercially acceptable
      means to protect Your Personal Data, We cannot guarantee its absolute
      security.
    </p>
    <br />
    <h2 class="font-bold">Children's Privacy</h2>
    <p>
      Our Service does not address anyone under the age of 13. We do not
      knowingly collect personally identifiable information from anyone under
      the age of 13. If You are a parent or guardian and You are aware that Your
      child has provided Us with Personal Data, please contact Us. If We become
      aware that We have collected Personal Data from anyone under the age of 13
      without verification of parental consent, We take steps to remove that
      information from Our servers.
    </p>
    <br />
    <h2 class="font-bold">Links to Other Websites</h2>
    <p>
      Our Service may contain links to other websites that are not operated by
      Us. If You click on a third party link, You will be directed to that third
      party's site. We strongly advise You to review the Privacy Policy of every
      site You visit.
    </p>
    <p>
      We have no control over and assume no responsibility for the content,
      privacy policies or practices of any third party sites or services.
    </p>
    <br />
    <h2 class="font-bold">Changes to this Privacy Policy</h2>
    <p>
      We may update Our Privacy Policy from time to time. We will notify You of
      any changes by posting the new Privacy Policy on this page.
    </p>
    <p>
      You are advised to review this Privacy Policy periodically for any
      changes. Changes to this Privacy Policy are effective when they are posted
      on this page.
    </p>
    <br />
    <h2 class="font-bold">Contact Us</h2>
    <p>
      If you have any questions about this Privacy Policy, You can contact us:
    </p>
    <ul>
      <li>By email: jsaylor@eoas.ubc.ca</li>
    </ul>
  </div>
</template>
